### ISSUE TITLE
Need help with the config - no rewards and hash at all

### ISSUE THREAD

**Issue by martin-karailiev** [8lecramm/derohe-proxy#3]
Hello and sorry for writing here but I have no idea how to contact you. I must be doing something wrong, as I start the proxy with the following command, but there is no hashrate reported anywhere, and I have no rewards all day. About 100kh machines are connected to it.

derohe-proxy --daemon-address=0.0.0.0:10100 --listen-address=0.0.0.0:11111 --log-interval=90 --pool --wallet-address=dero1...

The demon is running on the same machine. The miners are connected and can been seen in the proxy at 192.168.0.222:11111. If I point the miners direct to the demon there is no problem.

**Comment by 8lecramm** [comment]
Hi,
set `--daemon-address` to **127.0.0.1:10100** when the daemon is running on the same machine.
You can omit the `--pool` flag since you are solo mining.
